version: '3.4'

services:
  locationcapture:
    image: ${DOCKER_REGISTRY-}locationcapture
    build:
      context: .
      dockerfile: LocationCapture/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Database=LocationCaptureDb;User=sa;Password=password(*&^%$#@!)here;MultipleActiveResultSets=true"
      - "IdentityServer__Key__Type=Development"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=Your_password123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    restart: on-failure

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=password(*&^%$#@!)here"
      - "ACCEPT_EULA=Y"